version: "3.8"

#

services:
  server:
    container_name: server
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - dist:/usr/src/frontEndDist
    ports:
      - 80:8000
      - 443:8001
      - 5050:8002

  #

  front-end:
    container_name: front-end
    build:
      context: ./frontEnd
    volumes:
      - ./frontEnd:/usr/src/app
      - dist:/usr/src/app/dist
    ports:
      - 4200:4200

  #

  mongo:
    container_name: mongo
    image: mongo
    hostname: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017

#

volumes:
  dist:
